[build]
  publish = "dist/proyectoangular1/browser"
  command = "npm run build --if-present"

[build.environment]
  NODE_VERSION = "22.16.0"

[context.production.environment]
  NODE_VERSION = "22.16.0"
